### ISSUE TITLE
A que se debe este error en la instalación? :(

### ISSUE THREAD

**Issue by antonyayansi** [Yextep/Resu#1]
![image](https://github.com/Yextep/Resu/assets/83934616/c43ac001-d3d4-4c14-b5a8-b40dae5c8a73)

**Comment by Yextep** [comment]
Te está diciendo claramente que no se encontró ninguna distribución coincidente para gensim==3.8.3
Tienes que instalarla, haz lo siguiente.

sudo apt update
sudo apt upgrade
sudo pip install -r requeriments.txt

Si aún así te vuelve a dar error, escribe el siguiente comando:

sudo pip install gensim==3.8.3
